# Generated by Django 4.1.3 on 2022-12-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_delete_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Information',
        ),
    ]
